name: Build FFmpeg+whisper for Android (multi-ABI, API 34, shared)

on:
  workflow_dispatch:
    inputs:
      ffmpeg-tag:
        description: "FFmpeg git tag (e.g. n8.0)"
        required: true
        default: "n8.0"
      ndk-version:
        description: "Android NDK version (e.g. r27)"
        required: true
        default: "r27"
      whisper-tag:
        description: "whisper.cpp tag (>= v1.7.5)"
        required: true
        default: "v1.7.5"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        abi: [arm64-v8a, armeabi-v7a, x86_64]
    env:
      API_LEVEL: 34
    steps:
      - name: Checkout workflow files
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            git wget unzip build-essential pkg-config yasm cmake ninja-build \
            libc6:i386 libstdc++6:i386 lib32z1 gcc-multilib g++-multilib

      - name: Download Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-${{ github.event.inputs.ndk-version || 'r27' }}-linux.zip
          unzip -q -o android-ndk-${{ github.event.inputs.ndk-version || 'r27' }}-linux.zip
          echo "ANDROID_NDK_VERSION=${{ github.event.inputs.ndk-version || 'r27' }}" >> $GITHUB_ENV
          echo "NDK=$PWD/android-ndk-${{ github.event.inputs.ndk-version || 'r27' }}" >> $GITHUB_ENV

      - name: Clone FFmpeg
        run: |
          git clone https://github.com/FFmpeg/FFmpeg ffmpeg-src
          cd ffmpeg-src
          git fetch --tags
          git checkout ${{ github.event.inputs.ffmpeg-tag || 'n8.0' }}

      - name: Clone whisper.cpp
        run: |
          git clone --depth=1 -b ${{ github.event.inputs.whisper-tag || 'v1.7.5' }} https://github.com/ggerganov/whisper.cpp whisper-src

      - name: Set up toolchain and env for ${{ matrix.abi }}
        run: |
          NDK=$PWD/android-ndk-${{ github.event.inputs.ndk-version || 'r27' }}
          TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
          case "${{ matrix.abi }}" in
            arm64-v8a)
              export ARCH=arm64
              export CPU=armv8-a
              export ANDROID_ABI=arm64-v8a
              export CROSS_PREFIX=$TOOLCHAIN/bin/aarch64-linux-android-
              export CC=$TOOLCHAIN/bin/aarch64-linux-android${API_LEVEL}-clang
              export CXX=$TOOLCHAIN/bin/aarch64-linux-android${API_LEVEL}-clang++
              ;;
            armeabi-v7a)
              export ARCH=arm
              export CPU=armv7-a
              export ANDROID_ABI=armeabi-v7a
              export CROSS_PREFIX=$TOOLCHAIN/bin/arm-linux-androideabi-
              export CC=$TOOLCHAIN/bin/armv7a-linux-androideabi${API_LEVEL}-clang
              export CXX=$TOOLCHAIN/bin/armv7a-linux-androideabi${API_LEVEL}-clang++
              ;;
            x86_64)
              export ARCH=x86_64
              export CPU=x86-64
              export ANDROID_ABI=x86_64
              export CROSS_PREFIX=$TOOLCHAIN/bin/x86_64-linux-android-
              export CC=$TOOLCHAIN/bin/x86_64-linux-android${API_LEVEL}-clang
              export CXX=$TOOLCHAIN/bin/x86_64-linux-android${API_LEVEL}-clang++
              ;;
          esac
          export AR=$TOOLCHAIN/bin/llvm-ar
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          export NM=$TOOLCHAIN/bin/llvm-nm
          export ANDROID_PLATFORM=android-${API_LEVEL}

          echo "ARCH=$ARCH" >> $GITHUB_ENV
          echo "CPU=$CPU" >> $GITHUB_ENV
          echo "CROSS_PREFIX=$CROSS_PREFIX" >> $GITHUB_ENV
          echo "CC=$CC" >> $GITHUB_ENV
          echo "CXX=$CXX" >> $GITHUB_ENV
          echo "AR=$AR" >> $GITHUB_ENV
          echo "RANLIB=$RANLIB" >> $GITHUB_ENV
          echo "STRIP=$STRIP" >> $GITHUB_ENV
          echo "NM=$NM" >> $GITHUB_ENV
          echo "ANDROID_ABI=$ANDROID_ABI" >> $GITHUB_ENV
          echo "ANDROID_PLATFORM=$ANDROID_PLATFORM" >> $GITHUB_ENV

      - name: Build and install whisper.cpp for ${{ matrix.abi }}
        env:
          ANDROID_PLATFORM: ${{ env.ANDROID_PLATFORM }}
          ANDROID_ABI: ${{ env.ANDROID_ABI }}
          NDK: ${{ env.NDK }}
        run: |
          DEPS_PREFIX=$PWD/android-deps/${{ matrix.abi }}
          mkdir -p "$DEPS_PREFIX"/{lib,include,lib/pkgconfig}

          cmake -S whisper-src -B whisper-build-${{ matrix.abi }} -G Ninja \
            -DANDROID_NDK="$NDK" \
            -DCMAKE_TOOLCHAIN_FILE="$NDK/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI="$ANDROID_ABI" \
            -DANDROID_PLATFORM="$ANDROID_PLATFORM" \
            -DWHISPER_BUILD_TESTS=OFF \
            -DWHISPER_BUILD_EXAMPLES=OFF \
            -DWHISPER_BUILD_SHARED_LIB=OFF \
            -DCMAKE_BUILD_TYPE=Release

          cmake --build whisper-build-${{ matrix.abi }} --target whisper -j$(nproc)

          # 拷贝产物（静态库 + 头文件）
          cp whisper-build-${{ matrix.abi }}/libwhisper.a "$DEPS_PREFIX/lib/" || cp whisper-build-${{ matrix.abi }}/src/libwhisper.a "$DEPS_PREFIX/lib/"
          cp whisper-src/whisper.h "$DEPS_PREFIX/include/"

          # 生成最小 pkg-config 文件（版本按 whisper.cpp tag）
          cat > "$DEPS_PREFIX/lib/pkgconfig/whisper.pc" <<'EOF'
prefix=@PREFIX@
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: whisper
Description: Whisper inference library
Version: @VERSION@
Libs: -L${libdir} -lwhisper
Cflags: -I${includedir}
EOF
          sed -i "s|@PREFIX@|$DEPS_PREFIX|g" "$DEPS_PREFIX/lib/pkgconfig/whisper.pc"
          sed -i "s|@VERSION@|${{ github.event.inputs.whisper-tag || 'v1.7.5' }}|g" "$DEPS_PREFIX/lib/pkgconfig/whisper.pc"

          echo "PKG_CONFIG_PATH=$DEPS_PREFIX/lib/pkgconfig" >> $GITHUB_ENV

      - name: Clean before configure
        working-directory: ffmpeg-src
        run: |
          make distclean || true
          git clean -xdf || true

      - name: Configure FFmpeg for ${{ matrix.abi }} with whisper
        working-directory: ffmpeg-src
        env:
          ARCH: ${{ env.ARCH }}
          CPU: ${{ env.CPU }}
          CROSS_PREFIX: ${{ env.CROSS_PREFIX }}
          CC: ${{ env.CC }}
          AR: ${{ env.AR }}
          RANLIB: ${{ env.RANLIB }}
          STRIP: ${{ env.STRIP }}
          NM: ${{ env.NM }}
          PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH }}
        run: |
          mkdir -p ../android-build/${{ matrix.abi }}
          ./configure \
            --prefix=$PWD/../android-build/${{ matrix.abi }} \
            --target-os=android \
            --arch=$ARCH \
            --cpu=$CPU \
            --cross-prefix=$CROSS_PREFIX \
            --cc=$CC \
            --ar=$AR \
            --ranlib=$RANLIB \
            --strip=$STRIP \
            --nm=$NM \
            --enable-cross-compile \
            --enable-shared \
            --disable-static \
            --disable-doc \
            --disable-programs \
            --enable-pic \
            --disable-debug \
            $( [ "$ARCH" = "arm64" -o "$ARCH" = "arm" ] && echo "--enable-neon" ) \
            --enable-whisper \
            --extra-ldflags="-Wl,-z,max-page-size=16384"

      - name: Build FFmpeg for ${{ matrix.abi }}
        working-directory: ffmpeg-src
        run: |
          make -j$(nproc)
          make install

      - name: Copy config.h to output dir
        working-directory: ffmpeg-src
        run: cp config.h ../android-build/${{ matrix.abi }}/config.h

      - name: Upload ${{ matrix.abi }} build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-android-${{ matrix.abi }}
          path: android-build/${{ matrix.abi }}
