name: Build FFmpeg + Whisper for Android (multi-ABI, API 34, shared + ffmpeg_main.so)

on:
  workflow_dispatch:
    inputs:
      ffmpeg-tag:
        description: "FFmpeg git tag (e.g. n8.0)"
        required: true
        default: "n8.0"
      ndk-version:
        description: "Android NDK version (e.g. r27)"
        required: true
        default: "r27"
      whisper-tag:
        description: "whisper.cpp tag (>= v1.7.6)"
        required: true
        default: "v1.7.6"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        abi: [arm64-v8a, armeabi-v7a, x86_64]
    env:
      API_LEVEL: 34
      FFMPEG_TAG: ${{ inputs.ffmpeg-tag || 'n8.0' }}
      ANDROID_NDK_VERSION: ${{ inputs.ndk-version || 'r27' }}
      WHISPER_TAG: ${{ inputs.whisper-tag || 'v1.7.6' }}

    steps:
      - name: Checkout workflow files
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          set -e
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            git wget unzip build-essential pkg-config yasm nasm cmake ninja-build \
            libc6:i386 libstdc++6:i386 lib32z1 gcc-multilib g++-multilib
          nasm -v

      - name: Download Android NDK
        run: |
          set -e
          wget -q "https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip"
          unzip -q -o "android-ndk-${ANDROID_NDK_VERSION}-linux.zip"
          echo "NDK=$PWD/android-ndk-${ANDROID_NDK_VERSION}" >> "$GITHUB_ENV"

      - name: Clone FFmpeg
        run: |
          set -e
          git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg-src
          cd ffmpeg-src
          git fetch --tags
          git checkout "${FFMPEG_TAG}"

      - name: Clone whisper.cpp
        run: |
          set -e
          git clone --depth=1 -b "${WHISPER_TAG}" https://github.com/ggerganov/whisper.cpp.git whisper-src

      - name: Set up toolchain and env for ${{ matrix.abi }}
        run: |
          set -e
          NDK="$PWD/android-ndk-${ANDROID_NDK_VERSION}"
          TOOLCHAIN="$NDK/toolchains/llvm/prebuilt/linux-x86_64"

          case "${{ matrix.abi }}" in
            arm64-v8a)
              ARCH=arm64
              CPU=armv8-a
              ANDROID_ABI=arm64-v8a
              CROSS_PREFIX="$TOOLCHAIN/bin/aarch64-linux-android-"
              CC="$TOOLCHAIN/bin/aarch64-linux-android${API_LEVEL}-clang"
              CXX="$TOOLCHAIN/bin/aarch64-linux-android${API_LEVEL}-clang++"
              ;;
            armeabi-v7a)
              ARCH=arm
              CPU=armv7-a
              ANDROID_ABI=armeabi-v7a
              CROSS_PREFIX="$TOOLCHAIN/bin/arm-linux-androideabi-"
              CC="$TOOLCHAIN/bin/armv7a-linux-androideabi${API_LEVEL}-clang"
              CXX="$TOOLCHAIN/bin/armv7a-linux-androideabi${API_LEVEL}-clang++"
              ;;
            x86_64)
              ARCH=x86_64
              CPU=x86-64
              ANDROID_ABI=x86_64
              CROSS_PREFIX="$TOOLCHAIN/bin/x86_64-linux-android-"
              CC="$TOOLCHAIN/bin/x86_64-linux-android${API_LEVEL}-clang"
              CXX="$TOOLCHAIN/bin/x86_64-linux-android${API_LEVEL}-clang++"
              ;;
          esac

          {
            echo "ARCH=$ARCH"
            echo "CPU=$CPU"
            echo "ANDROID_ABI=$ANDROID_ABI"
            echo "CROSS_PREFIX=$CROSS_PREFIX"
            echo "CC=$CC"
            echo "CXX=$CXX"
            echo "AR=$TOOLCHAIN/bin/llvm-ar"
            echo "RANLIB=$TOOLCHAIN/bin/llvm-ranlib"
            echo "STRIP=$TOOLCHAIN/bin/llvm-strip"
            echo "NM=$TOOLCHAIN/bin/llvm-nm"
            echo "OBJCOPY=$TOOLCHAIN/bin/llvm-objcopy"
            echo "ANDROID_PLATFORM=android-${API_LEVEL}"
          } >> "$GITHUB_ENV"

      - name: Build whisper.cpp for ${{ matrix.abi }}
        run: |
          set -euo pipefail
          DEPS_PREFIX="$PWD/android-deps/${{ matrix.abi }}"
          mkdir -p "$DEPS_PREFIX"/{lib,include,lib/pkgconfig}

          cmake -S whisper-src -B "whisper-build-${{ matrix.abi }}" -G Ninja \
            -DANDROID_NDK="$NDK" \
            -DCMAKE_TOOLCHAIN_FILE="$NDK/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI="$ANDROID_ABI" \
            -DANDROID_PLATFORM="$ANDROID_PLATFORM" \
            -DBUILD_SHARED_LIBS=ON \
            -DWHISPER_BUILD_TESTS=OFF \
            -DWHISPER_BUILD_EXAMPLES=OFF \
            -DCMAKE_BUILD_TYPE=Release

          cmake --build "whisper-build-${{ matrix.abi }}" -j"$(nproc)"

          # Copy libs
          if [ -f "whisper-build-${{ matrix.abi }}/src/libwhisper.so" ]; then
            cp "whisper-build-${{ matrix.abi }}/src/libwhisper.so" "$DEPS_PREFIX/lib/"
          elif [ -f "whisper-build-${{ matrix.abi }}/libwhisper.so" ]; then
            cp "whisper-build-${{ matrix.abi }}/libwhisper.so" "$DEPS_PREFIX/lib/"
          else
            echo "libwhisper.so not found"
            find "whisper-build-${{ matrix.abi }}" -name "*.so" -type f
            exit 1
          fi

          # Copy ggml-related shared libs
          find "whisper-build-${{ matrix.abi }}" -maxdepth 3 -type f -name "libggml*.so" -exec cp -v {} "$DEPS_PREFIX/lib/" \; || true

          # Headers
          if [ -f "whisper-src/include/whisper.h" ]; then
            cp "whisper-src/include/whisper.h" "$DEPS_PREFIX/include/"
          elif [ -f "whisper-src/whisper.h" ]; then
            cp "whisper-src/whisper.h" "$DEPS_PREFIX/include/"
          else
            find whisper-src -name "whisper.h" -type f -exec cp {} "$DEPS_PREFIX/include/" \;
          fi

          if [ -f "whisper-src/ggml/include/ggml.h" ]; then
            cp "whisper-src/ggml/include/ggml.h" "$DEPS_PREFIX/include/"
          elif [ -f "whisper-src/ggml.h" ]; then
            cp "whisper-src/ggml.h" "$DEPS_PREFIX/include/"
          else
            find whisper-src -name "ggml.h" -type f -exec cp {} "$DEPS_PREFIX/include/" \;
          fi

          find whisper-src -name "ggml*.h" -type f -exec cp {} "$DEPS_PREFIX/include/" \; || true

          echo "DEPS_PREFIX=$DEPS_PREFIX" >> "$GITHUB_ENV"

      - name: Create whisper.pc (include ggml libs)
        run: |
          set -euo pipefail
          WHISPER_VER="${WHISPER_TAG#v}"
          PC_FILE="$DEPS_PREFIX/lib/pkgconfig/whisper.pc"

          GGML_LIBS=""
          if ls "$DEPS_PREFIX/lib"/libggml*.so >/dev/null 2>&1; then
            for f in "$DEPS_PREFIX/lib"/libggml*.so; do
              b="$(basename "$f")"
              n="${b#lib}"; n="${n%.so}"
              GGML_LIBS="$GGML_LIBS -l${n}"
            done
          fi

          {
            echo "prefix=$DEPS_PREFIX"
            echo "exec_prefix=\${prefix}"
            echo "libdir=\${prefix}/lib"
            echo "includedir=\${prefix}/include"
            echo ""
            echo "Name: whisper"
            echo "Description: Whisper inference library (with ggml backends)"
            echo "Version: $WHISPER_VER"
            echo "Libs: -L\${libdir} -lwhisper${GGML_LIBS}"
            echo "Cflags: -I\${includedir}"
          } > "$PC_FILE"

          echo "Created $PC_FILE:"
          cat "$PC_FILE"

      - name: Verify whisper pkg-config
        run: |
          set -e
          export PKG_CONFIG_PATH="$DEPS_PREFIX/lib/pkgconfig"
          export PKG_CONFIG_LIBDIR="$DEPS_PREFIX/lib/pkgconfig"
          echo "pkg-config --cflags whisper:"
          pkg-config --cflags whisper || true
          echo "pkg-config --libs whisper:"
          pkg-config --libs whisper || true
          echo "All files in deps:"
          find "$DEPS_PREFIX" -type f | sort

      - name: Clean FFmpeg tree
        working-directory: ffmpeg-src
        run: |
          set -e
          make distclean || true
          git clean -xdf || true

      - name: Configure FFmpeg for ${{ matrix.abi }} (build ffmpeg CLI)
        working-directory: ffmpeg-src
        run: |
          set -euo pipefail
          export PKG_CONFIG_PATH="$DEPS_PREFIX/lib/pkgconfig"
          export PKG_CONFIG_LIBDIR="$DEPS_PREFIX/lib/pkgconfig"
          mkdir -p "../android-build/${{ matrix.abi }}"

          NEON_FLAG=""
          if [ "$ARCH" = "arm64" ] || [ "$ARCH" = "arm" ]; then
            NEON_FLAG="--enable-neon"
          fi

          ./configure \
            --prefix="$PWD/../android-build/${{ matrix.abi }}" \
            --target-os=android \
            --arch="$ARCH" \
            --cpu="$CPU" \
            --cross-prefix="$CROSS_PREFIX" \
            --cc="$CC" \
            --ar="$AR" \
            --ranlib="$RANLIB" \
            --strip="$STRIP" \
            --nm="$NM" \
            --pkg-config="$(which pkg-config)" \
            --enable-cross-compile \
            --enable-shared \
            --disable-static \
            --disable-doc \
            --disable-ffprobe \
            --disable-ffplay \
            --enable-pic \
            --disable-debug \
            $NEON_FLAG \
            --extra-libs="$(pkg-config --libs whisper)" \
            --extra-ldflags="-Wl,-z,max-page-size=16384"

      - name: Build FFmpeg for ${{ matrix.abi }}
        working-directory: ffmpeg-src
        run: |
          set -e
          make -j"$(nproc)"
          make install

      - name: Build libffmpeg_entry.so (export ffmpeg_main) and header
        working-directory: ffmpeg-src
        run: |
          set -euo pipefail
          OUT_LIB="$PWD/../android-build/${{ matrix.abi }}/lib"
          OUT_INC="$PWD/../android-build/${{ matrix.abi }}/include"
          mkdir -p "$OUT_LIB" "$OUT_INC"

          # 1) Rename main -> ffmpeg_main in fftools/ffmpeg.o
          cp fftools/ffmpeg.o fftools/ffmpeg_main.o
          "$OBJCOPY" --redefine-symbol main=ffmpeg_main fftools/ffmpeg_main.o

          # 2) Collect fftools objects (exclude ffplay/ffprobe/original ffmpeg.o)
          mapfile -t FFOBJS < <(find fftools -type f -name '*.o' \
            ! -name 'ffplay*' ! -name 'ffprobe*' ! -name 'ffmpeg.o' | sort)
          FFOBJS=("fftools/ffmpeg_main.o" "${FFOBJS[@]}")

          echo "Linking libffmpeg_entry.so with objects:"
          printf '  %s\n' "${FFOBJS[@]}"

          # 3) Link shared library with all deps
          "$CC" -shared -o "$OUT_LIB/libffmpeg_entry.so" \
            "${FFOBJS[@]}" \
            -L"$OUT_LIB" \
            -lavfilter -lavformat -lavdevice -lswscale -lavcodec -lswresample -lavutil \
            $(pkg-config --libs whisper) \
            -lm -lz -llog \
            -Wl,-z,max-page-size=16384

          # 4) Header for JNI call
          cat > "$OUT_INC/ffmpeg_entry.h" <<'EOF'
          #ifndef FFMPEG_ENTRY_H
          #define FFMPEG_ENTRY_H
          #ifdef __cplusplus
          extern "C" {
          #endif
          // Example:
          //   const char* argv[] = {"ffmpeg", "-nostdin", "-h", 0};
          //   int ret = ffmpeg_main(3, (char**)argv);
          int ffmpeg_main(int argc, char **argv);
          #ifdef __cplusplus
          }
          #endif
          #endif // FFMPEG_ENTRY_H
          EOF

          echo "Built: $OUT_LIB/libffmpeg_entry.so"
          "$NM" -D "$OUT_LIB/libffmpeg_entry.so" | grep -E ' ffmpeg_main$' || true
          ls -la "$OUT_INC/ffmpeg_entry.h"

      - name: Show outputs
        run: |
          set -e
          echo "=== Installed files for ${{ matrix.abi }} ==="
          find "android-build/${{ matrix.abi }}" -type f | sort

      - name: Upload ${{ matrix.abi }} build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-android-${{ matrix.abi }}
          path: android-build/${{ matrix.abi }}
